### ISSUE TITLE
how can i use it in cad with old vision

### ISSUE THREAD

**Issue by diablo333** [luanshixia/AutoCADCodePack#10]
how can i use it in cad with old vision

**Comment by luanshixia** [comment]
We used to target R18 (as old as 2010). You can use our early release
https://github.com/luanshixia/AutoCADCodePack/releases

Also, it should not be difficult to change the framework and dependency of the latest code to fit your needs if you want the new features.

**Comment by diablo333** [comment]
very think, my english is bad , can i use chinese ,i guess you are chinese 


921421319@qq.com
 
From: Yang Wang
Date: 2018-09-15 07:31
To: luanshixia/AutoCADCodePack
CC: diablo333; Author
Subject: Re: [luanshixia/AutoCADCodePack] how can i use it in cad with old vision (#10)
We used to target R18 (as old as 2010). You can use our early release
https://github.com/luanshixia/AutoCADCodePack/releases
Also, it should not be difficult to change the framework and dependency of the latest code to fit your needs if you want the new features.

**Comment by luanshixia** [comment]
Yes.

**Comment by diablo333** [comment]
hello，the new vision   can support autocad 2019  and   can it  run in atuocad 2018 ?



921421319@qq.com
 
From: Yang Wang
Date: 2018-09-16 13:33
To: luanshixia/AutoCADCodePack
CC: diablo333; Author
Subject: Re: [luanshixia/AutoCADCodePack] how can i use it in cad with old vision (#10)
Yes.

**Comment by luanshixia** [comment]
We haven't done test against 2018. The binary is probably not compatible with 2018, but again you can always rebuild with minimal changes to the source code.
