### ISSUE TITLE
Use the new release in older AutoCAD.

### ISSUE THREAD

**Issue by Joao-Bosco-de-Carvalho-Junior** [luanshixia/AutoCADCodePack#12]
Hello, I don't know how to  "target other versions with the source files and build yourself".
I use Visual Studio 2019 and AutoCAD 2013.

Could you explain this better, please?

Thank you!

**Comment by luanshixia** [comment]
Replace the Nuget references with references to the .dll files from the AutoCAD 2013 .NET SDK.

The commit to update to use Nuget is here:
https://github.com/luanshixia/AutoCADCodePack/commit/9cd9a8de6521d8171b67d57fcc9f9f2bfca93e4d#diff-35d814bb6f9b1c35116318e1a5ab2f8a

Basically you want to revert the changes to the references in the .csproj file.

**Comment by luanshixia** [comment]
I am working on publishing binary releases for major AutoCAD versions. Will keep this page posted.
