### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by SolitaryFox** [luanshixia/AutoCADCodePack#9]
你好 我在使用过程中发现一个错误  在DBhelper.cs文件中693行 `//          return objectIds.Select(id => id.Database).Single();
            return objectIds.Select(id => id.Database).Distinct().Single();` 这里当序列中元素不止一个的时候Select得到的集合元素不止一个 调用Single()会抛异常。  在执行test.cs   SelectByLayer 命令的时候。这里实际上获得的所有元素是同一个。

**Comment by luanshixia** [comment]
能给出具体的repro吗？
这里是假设所有操作都是在一个DWG里。你是在什么情况下取到了不同文件里的对象？

**Comment by SolitaryFox** [comment]
你好 我使用的是 autocad 2017 ，在只打开了一个文件的情况下  执行 test.cs SelectByLayer 就会出现这个异常

**Comment by luanshixia** [comment]
多谢指正！已修复。
